# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink:           none

# Setup
title:               Blog
tagline:             'Ideas worth spreading'
description:         'PengfeiFan'
url:                 https://github.com/pengfeifan
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Pengfei Fan
  url:               https://pengfeifan.github.io/
  email:             pengfei.fan@hotmail.com

# Custom vars
version:             1.0

# Social Media
github:				https://github.com/pengfeifan
twitter:			http://twitter.com/pengfeifan
disqus:             blog-github-io

# Theme Author 
theme:
  creator:			WilliamFan
  codename:			Blog
  link:         https://github.com/pengfeifan
